# Thesis Checklist

Print this page off and check of each task as you complete them. 


| Task           | Date Due | Finished | 
|----------------|---------------|-----------|
| Passing Grade PSYC564 | Spring Year 1 | [ ] |
| Academic Good Standing | Entire Program  | [ ]  |
| Topic Approved | Summer First Year | [ ] Director<br/>[ ] Instructor |
| Committee Assignment | Fall 2nd Year | [ ] Chair<br/>[ ] Reader |
| IRB | Fall 2nd Year  | [ ] Draft<br/>[ ] Submitted |
| Literature Review |Fall 2nd Year  | [ ]  |
| Method Section | Entire Program | [ ]  |
| Power Analysis | Fall 2nd Year | [ ]  |
| R Code | Fall 2nd Year  | [ ]  |
| Preregister Study | Fall 2nd Year | [ ] Draft<br/>[ ] Submitted |
| Passing Grade PSYC565 | Fall 2nd Year | [ ]  |
| Register for PSYC566 | End of Fall 2nd Year  | [ ]  |
| OSF made Public | Spring Year 2  | [ ]  |
| OSF include Reproducible R Code | Spring 2nd Year  | [ ]  |
| Thesis Commons | End of Spring 2nd Year | [ ]  |
| Thesis Binding | Optional | [ ]  |
| GitHub Blog | Optional | [ ]  |
| Shiny App | Optional | [ ]  |

Dr. Bedics will review that the above steps were successfully passed before assigning a thesis grade. Students that require more time to complete the thesis after the 2nd year will have to pay a thesis continuation fee each semester required to complete the thesis. 
