# Thesis Binding


## General 

The following are instructions for binding your thesis.  The binding of your thesis is _optional_ and at your expense.You are responsible for the spelling, grammar, and correct APA formatting of your thesis. A bound thesis is a **final** thesis.  

## Cover Pages and Paper Formatting

After the title page, signature page, abstract, and table of contents you will insert the rest of your paper in APA format.  Please see the binding document the MSCP Google Drive.

## Final Submission for Binding

1.	At least three (3) bound copies of the Thesis must be ordered.
a.	One copy for the Graduate School of Psychology, one copy for the Thesis Committee Chair, and one personal copy for your possession. You can order more if you prefer (see #2). 
b.	The three copies must be printed on 25% rag or cotton fiber watermarked white paper, at least 20 pound weight, 8½ x 11 inches in size (EZERASE, or similar paper is not acceptable). A good example is Southworth Fine Business Paper, 25% cotton, 24 pound, white, stock #403C which is available for purchase from Office Depot, OfficeMax, and Staples. A similar 20 pound weight paper is also available. 
c.	Original signed signature pages on the same paper must be submitted with each of the three copies.
2.	Additional personal copies may be ordered at the same time.
a.	Personal copies may be printed on paper of the student’s choice (e.g., 20 pound paper).
b.	Signature pages for the personal copies may be photocopies of the originals as long as they are on paper that is identical to the rest of the thesis.
3.	Copies for binding must be delivered to the Program Specialist. 
a.	The copies delivered to the Program Specialist are NOT to be bound - just packaged with bright colored paper separating the individual copies.
b.	Students are responsible for paying binding fees for all copies (the three required copies and for any additional personal copies). The cost is $40 per copy (no matter the length), and to be paid by check to CLU.  Prices may change.
c.	The Program Specialist will forward the copies to the bindery as they are delivered.
d.	Once the Program Specialist receives the copies and payment for binding, a change of grade will be submitted to the Registrar’s Office.
4.	The bound copies are typically ready in about 6-8 weeks and are distributed as follows:
a.	The Graduate School of Psychology copy and the Thesis Committee Chair copy will be delivered via campus mail by the Program Specialist.
b.	Students will be notified when their personal copies are ready for pick-up.
5.	If you have any questions regarding the binding process, please do not hesitate to contact Mengmeng Liu, Graduate Program Specialist, at 805-493-3662 or at mengmengliu@callutheran.edu.


