--- 
title: "CLU MSCP Thesis Handbook"
author: "Jamie Bedics, Ph.D., ABPP"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: jdbedics/clu-mscp-thesis-handbook
description: "Guidelines for complete the thesis for the MS in Clinical Psychology Program at CLU."
---

# Introduction {-}

The following information provides tips and guideance for the successful completion of the Thesis or Thesis Project in the MS in Clinical Psychology Program at California Lutheran University.

## Full Thesis Option

In this option you will take the research seminar class (565) in the Fall and also take thesis units in the Spring (there is, however, no class meeting). The full thesis option includes the development of your own independent research project which typically include the collection, analysis, and publication of data. 

Courses in your second year include:

| Class          | Semester | Units | 
|----------------|---------------|-----------|
| Research Seminar (565) | Fall | 3 |
| ABA | Fall  | # |
| Specialization Part I | Fall | 3 |
| Thesis Units (566) | Spring | 3 |
| Specialization Part II | Spring | 3 |


## Full Comprehensive Exam Option

If you decided, 100%, on comprehensive exams and will not take the Research Seminar in the Fall:

Courses in your second year include:

| Class          | Semester | Units | 
|----------------|---------------|-----------|
| ABA | Fall  | 3  |
| Specialization Part I | Fall | 3 |
| Elective | Spring | 3 |
| Specialization Part II | Spring | 3 |
| Comprehensive Exam | Spring | 0 |

The elective (3-units) could be Part II of any specialization or anything that Dr. Bedics approves.  The 3-units are required to make up for not having the Research Seminar in the Fall. You also want to take this in the Spring b/c if you take in the Fall you will only have 3 units in the spring which will make you less than part-time (not good!).



## Thesis **lite** Version

Here you can take the Research Seminar (565) in the Fall but not complete the thesis in the spring. People do this when they want to start a research project but then use it as a launching pad for a dissertation so they do not collect data in the Spring.  People also use this when they start the thesis with the intent to collect data but things do not work out with their sample or other issues come up that would prevent completion of the thesis.

Courses in your second year include:

| Class          | Semester | Units | 
|----------------|---------------|-----------|
| Research Seminar (565) | Fall | 3 |
| ABA | Fall  | 3  |
| Specialization Part I | Fall | 3 |
| Specialization Part II | Spring | 3 |
| Comprehensive Exam | Spring | 0 |

In this situation, the Research seminar in the Fall has served as your elective.  You can, if you like, take another elective if you want to keep you at part-time.